molgenis/molgenis-service-armadillo

pom.xml, src/main/java/org/molgenis/datashield/DatashieldServiceApplication.java, src/main/java/org/molgenis/datashield/r/RConnectionFactoryImpl.java, src/main/resources/application.yml
Bit unsure since while refactoring I noticed the retry is not getting called(!)
=> refactor: use spring retry for the connection retry mechanism

datashield/src/main/java/org/molgenis/datashield/DataController.java, datashield/src/test/java/org/molgenis/datashield/DataControllerTest.java
Setting it to true will make the execution return immediately.
=> feat(DataController): add async parameter to execute endpoint

datashield/pom.xml, datashield/src/main/java/org/molgenis/datashield/DataController.java, datashield/src/main/resources/application.yml, datashield/test.http, pom.xml
Uses spring boot actuator's info endpoint to give server info to the client.﻿
=> feat: info endpoint

armadillo/pom.xml, armadillo/src/main/resources/application.yml, pom.xml
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes
=> chore: upgrade to spring boot 2.3.1

armadillo/src/main/java/org/molgenis/armadillo/command/impl/ArmadilloCommandImpl.java, armadillo/src/main/java/org/molgenis/armadillo/interceptor/MDCInterceptor.java, armadillo/src/main/java/org/molgenis/armadillo/interceptor/WebConfig.java, armadillo/src/main/resources/application.yml
=> feat: log session ID

armadillo/src/main/java/org/molgenis/armadillo/command/impl/CommandsImpl.java, armadillo/src/test/java/org/molgenis/armadillo/command/impl/CommandsImplTest.java
=> fix: do not retrieve result of assignment

r/src/main/java/org/molgenis/r/service/RExecutorServiceImpl.java
The RFileOutputStream that we use is not buffered, after experimenting some it looks like adding a buffer will speed up performance quite significantly.
Transfer times for different buffer sizes of the copy buffer (red) and output stream buffer (blue)
=> fix: buffer R file outputstream

docker/docker-compose.yml, docker/rebuild.sh, docker/rserver/Dockerfile, r/src/main/java/org/molgenis/r/service/PackageServiceImpl.java, r/src/test/java/org/molgenis/r/service/PackageServiceImplTest.java
=> chore: make it easier to add dsDanger in dev environment

armadillo/http/test-tutorial.http, armadillo/http/test.http
The test data was changed without updating the http files
=> Fix HTTP examples

pom.xml
Reverts molgenis/molgenis-service-armadillo#182
=> Revert "Update spring boot to v2.7.1"

armadillo/src/main/resources/application.yml
See https://stackoverflow.com/questions/61956227/csrf-support-in-springdoc-openapi-swagger-ui
=> Enable CSRF token in Swagger UI

pom.xml
also
- added organize imports
- automatically format on compile
=> dep: coveo.fmt has moved to spotify

armadillo/http/http-client.env.json, armadillo/http/test-actuator.http, armadillo/http/test-exceptions.http, armadillo/http/test-profiles.http, armadillo/http/test-resources.http, armadillo/http/test-tutorial.http, armadillo/http/test-workspaces.http, armadillo/http/test.http
Makes it possible to run http tests in different environments
=> Add http env file

armadillo/pom.xml, armadillo/src/main/java/org/molgenis/armadillo/interceptor/WebConfig.java, ui/vite.config.js
Will serve the build from the ui module on /ui
=> feat: serve ui as part of armadillo java app (on /ui)

ui/src/App.vue, ui/src/api/api.ts, ui/src/helpers/errorProcessing.ts, ui/src/helpers/errors.ts
because the name connection error is not always correct
fix #317
=> fix(errors): rename ConnectionError to ApiError

ui/src/views/Users.vue
replace user plus icon with regular lg icon
fix #327
=> fix(users): make plus icon consistent with other screens

ui/src/helpers/errorProcessing.ts, ui/src/views/Profiles.vue, ui/src/views/Projects.vue, ui/src/views/ProjectsExplorer.vue, ui/src/views/Users.vue
replace incorrect hardcoded text in error
fix #326
=> fix(errors): make errormessage generic

ui/src/types/types.d.ts, ui/src/views/Profiles.vue
Ask for confirmation when deleting profile
fix #331
=> fix(profiles): add confirmation dialogs to profiles

ui/src/views/Profiles.vue
=> fix: profile buttons stays disabled after a row is edited

ui/src/views/Profiles.vue, ui/src/views/Users.vue
to prevent issues from happening when email is cleared before changing it
fix #361
=> fix(users): make email immutable

ui/src/components/FileUpload.vue, ui/src/components/ProfileStatus.vue
=> fix: console warnings

armadillo/src/main/java/org/molgenis/armadillo/audit/AuditEventPublisher.java, armadillo/src/test/java/org/molgenis/armadillo/audit/AuditEventPublisherTest.java
=> fix: email principal not shown for jwt class

ui/src/helpers/utils.ts, ui/src/views/ProjectsExplorer.vue
Alter sortAlphabetically function to be able to handle string objects and string arrays and call the function in the project explorer as well
fix #390
=> fix(projectexplorer): alphabetically sort folders and files

.circleci/config.yml, build.gradle
try to do this in branch to no polute our log
=> build: fix release

ui/index.html
to solve warning, files in public folder are served on root
=> fix(favicon): load favicon from root

.circleci/config.yml, armadillo/src/main/java/org/molgenis/armadillo/controller/StorageController.java
Make getObject streaming.
fixes #441
=> fix(StorageController): cannot load large resources

armadillo/src/main/java/org/molgenis/armadillo/controller/StorageController.java, armadillo/src/main/java/org/molgenis/armadillo/storage/ArmadilloStorageService.java
Preauthorize users in the attached projects and SU for all functions used in downloading an object (resource) fixes #449
=> fix: grant permissions for downloading objects

ui/src/views/Profiles.vue
replace armadillo molgenis/armadillo:latest with datashield/armadillo-rserver
#371
=> fix(profiles): set armadillo r server to be default profile image

ui/src/helpers/utils.ts, ui/src/views/ProjectsExplorer.vue
fix console errors, warnings, typescript errors, folder being closed when file is uploaded and swapped file and folder names in delete function
=> fix(projects explorer): fix several issues in the project explorer

armadillo/src/main/java/org/molgenis/armadillo/audit/AuditEventPublisher.java, armadillo/src/main/java/org/molgenis/armadillo/controller/StorageController.java, armadillo/src/main/java/org/molgenis/armadillo/storage/ArmadilloStorageService.java, armadillo/src/main/java/org/molgenis/armadillo/storage/FileInfo.java, armadillo/src/main/java/org/molgenis/armadillo/storage/LocalStorageService.java, armadillo/src/main/java/org/molgenis/armadillo/storage/MinioStorageService.java, armadillo/src/main/java/org/molgenis/armadillo/storage/ParquetUtils.java, armadillo/src/main/java/org/molgenis/armadillo/storage/StorageService.java, armadillo/src/test/java/org/molgenis/armadillo/controller/StorageControllerTest.java, armadillo/src/test/java/org/molgenis/armadillo/storage/LocalStorageServiceTest.java, armadillo/src/test/java/org/molgenis/armadillo/storage/ParquetUtilsTest.java
Create endpoint for retrieving information from files to be included in the UI later.
=> feat: get file info

scripts/Pipfile, scripts/Pipfile.lock, scripts/export-users.py
- Created Python script to extract cohorts and users from a fusion auth url and map the users to their corresponding cohort.
- Added pandas and numpy to Pipfile
=> Feat: extract users cohorts script

armadillo/src/main/resources/application.yml, scripts/install/armadillo-setup.sh
=> Make custom application.yml additional.

ui/src/views/Profiles.vue
In `ui/src/views/Profiles.vue`
=> Fix 2 types of red lines in vs code.

armadillo/src/main/java/org/molgenis/armadillo/controller/StorageController.java
Test using swagger. Login on `localhost:8080`, then go to the swagger page (http://localhost:8080/swagger-ui/index.html#/storage/downloadObject). 
Click "Try it out", Fill in a project and non existent object and click execute. 
See a 404 with a json response body, something like:
``` json
{
"timestamp": "2023-11-03T12:44:37.901+00:00",
"status": 404,
"error": "Not Found",
"message": "Project 'project' does not exist",
"path": "/storage/projects/project/objects/object"
}
```
Before the body used to be empty.
=> fix: #535 object endpoint doesnt return responsebody on error

ui/README.md, ui/src/views/Profiles.vue, ui/tests/unit/views/Profiles.spec.ts
=> Require an image version like :latest

armadillo/build.gradle, build.gradle, r/build.gradle
As requested in #543 this PR upgrades to Gradle-8.0.0
=> Upgrade to gradle-8.0.0

docs/ops/installing.md, scripts/install/README.md, scripts/install/armadillo-setup.sh
Let's not do script renames ;-)
Fixed some docs too.
=> quirk with setup script rename and DRY

CONTRIBUTING.md, docker/ci/README.md, docker/ci/application.yml
This is only docs triggered by #636 to test locally.
It seems a hickup as locally on MacOS ran 4 times (fail, fail, success, success)
=> fix:CDCD docs for local tests.

docker/ci/application.yml, scripts/release/README.md, scripts/release/install_release_script_dependencies.R, scripts/release/release-test.R
Added dsMTL test. Note these operations take a long time to run so I've only tested one function from this package.
=> test: Test/dsmtl

CONTRIBUTING.md
... and conventional commits + when a commit message will result in version bump + release
=> docs(CONTRIBUTING.md): clarify use of commit messages

docs/upgrade-3-4.md
Updated documentation for the armadillo 3 to 4 update after trying out the current manual.
=> docs: update documentation for armadillo 3 to 4 update

.github/pull_request_template.md
=> chore: Create pull_request_template.md. closes #680

armadillo/src/main/java/org/molgenis/armadillo/storage/LocalStorageService.java, armadillo/src/main/java/org/molgenis/armadillo/storage/ParquetUtils.java, armadillo/src/test/java/org/molgenis/armadillo/storage/LocalStorageServiceTest.java, armadillo/src/test/java/org/molgenis/armadillo/storage/ParquetUtilsTest.java, ui/src/helpers/utils.ts, ui/src/views/ProjectsExplorer.vue, ui/tests/unit/helpers/utils.spec.ts
how to test:
- create linkfile in UI
- go to location of linkfile
- see preview of linked table
todo:
=> Feat: M10506 UI link file view

armadillo/src/main/java/org/molgenis/armadillo/storage/ParquetUtils.java, ui/src/api/api.ts, ui/src/components/FileExplorer.vue, ui/src/components/SimpleTable.vue, ui/src/components/VariableSelector.vue, ui/src/components/ViewEditor.vue, ui/src/helpers/utils.ts, ui/src/types/types.d.ts, ui/src/views/ProjectsExplorer.vue, ui/tests/unit/components/SimpleTable.spec.ts, ui/tests/unit/components/VariableSelector.spec.ts, ui/tests/unit/helpers/utils.spec.ts, ui/tests/unit/views/ProjectExplorer.spec.ts, ui/yarn.lock
NB: Look at this one after: #728 is merged (this one contains commits of that one, once that one's merged, it will all make sense again)
how to test:
- open project with linkfile (or create link)
- select existing linkfile
- see that the source is shown above the preview table
- click edit 
- edit variables
- save
- open linkfile again
- see variables changed
todo:
=> Feat: M10506 UI linkfile edit

armadillo/src/main/java/org/molgenis/armadillo/storage/ParquetUtils.java, ui/src/api/api.ts, ui/src/components/FileExplorer.vue, ui/src/components/SimpleTable.vue, ui/src/components/VariableSelector.vue, ui/src/components/ViewEditor.vue, ui/src/helpers/utils.ts, ui/src/types/types.d.ts, ui/src/views/ProjectsExplorer.vue, ui/tests/unit/components/SimpleTable.spec.ts, ui/tests/unit/components/VariableSelector.spec.ts, ui/tests/unit/helpers/utils.spec.ts, ui/tests/unit/views/ProjectExplorer.spec.ts, ui/yarn.lock
=> Revert "Feat: M10506 UI linkfile edit"

.circleci/config.yml
how to test:
- see if sonar is visible in the PR
=> chore: try to get sonar to work

ui/src/App.vue, ui/src/api/api.ts, ui/src/components/ActuatorItem.vue, ui/src/components/Alert.vue, ui/src/helpers/utils.ts, ui/tests/unit/helpers/utils.spec.ts
=> feat: disk warning

scripts/install/armadillo-setup.sh
Fix  in script for config version.
=> Fix: Config not downloaded

ui/package.json, ui/yarn.lock
Reverts molgenis/molgenis-service-armadillo#692
=> Revert "fix(deps): update dependency bootstrap to v5.3.3"

docs/ui.md
Replace DataSHIELD standard profiles overview url
how to test:
- please check the url, you should not get a 404 ;)
todo:
=> Update ui.md profiles url

armadillo/build.gradle, armadillo/src/main/java/org/molgenis/armadillo/exceptions/InvalidObjectNameException.java, armadillo/src/main/java/org/molgenis/armadillo/info/RProcessEndpoint.java, armadillo/src/main/java/org/molgenis/armadillo/profile/ProfileScope.java, armadillo/src/main/java/org/molgenis/armadillo/storage/ArmadilloStorageService.java, armadillo/src/main/java/org/molgenis/armadillo/storage/ArmadilloWorkspace.java, armadillo/src/test/java/org/molgenis/armadillo/storage/ArmadilloLinkFileTest.java, armadillo/src/test/java/org/molgenis/armadillo/storage/ArmadilloStorageServiceTest.java, armadillo/src/test/java/org/molgenis/armadillo/storage/ArmadilloWorkspaceTest.java, r/build.gradle, ui/src/App.vue, ui/src/api/api.ts, ui/src/components/DataPreviewTable.vue, ui/src/components/FormValidation.vue, ui/src/components/ViewEditor.vue, ui/src/helpers/utils.ts, ui/src/types/types.d.ts, ui/src/views/ProjectsExplorer.vue
This is just a version bump of spotless and a reformat of the code that was formatted incorrectly due to outdated spotless version.
how to test:
- Go to https://preview-armadillo-pr-814.dev.molgenis.org/
- Click around to see if nothing weird happens
todo:
=> chore: fix spotless

.github/workflows/docs.yml
=> chore: add workflow to build docs using actions

ui/src/views/Profiles.vue
how to test:
- open profiles page in preview (http://preview-armadillo-pr-839.dev.molgenis.org/_
- see loading spinner
=> fix: #838 show loading spinner when opening profiles page in UI

README.md
=> BREAKING CHANGE!: bump version

README.md
=> fix!: Try and trigger version bump

settings.gradle
Reverts molgenis/molgenis-service-armadillo#856
=> fix: Revert "chore(deps): update plugin com.mooltiverse.oss.nyx to v3"

armadillo/src/main/java/org/molgenis/armadillo/storage/CharacterSeparatedFile.java, armadillo/src/test/java/org/molgenis/armadillo/storage/CharacterSeparatedFileTest.java
=> fix: also take typing into account when writing parquet file

.circleci/config.yml
Try to increase wait time so hopefully image is pulled when preview is spinning up.
how to test:
todo:
=> fix: Update config.yml

armadillo/src/main/java/org/molgenis/armadillo/audit/AuditEventPublisher.java, armadillo/src/main/java/org/molgenis/armadillo/controller/StorageController.java, armadillo/src/main/java/org/molgenis/armadillo/model/ArmadilloColumnMetaData.java, armadillo/src/main/java/org/molgenis/armadillo/storage/ArmadilloStorageService.java, armadillo/src/main/java/org/molgenis/armadillo/storage/LocalStorageService.java, armadillo/src/main/java/org/molgenis/armadillo/storage/ParquetUtils.java, armadillo/src/main/java/org/molgenis/armadillo/storage/StorageService.java, armadillo/src/test/java/org/molgenis/armadillo/controller/StorageControllerTest.java, armadillo/src/test/java/org/molgenis/armadillo/storage/ArmadilloStorageServiceTest.java, armadillo/src/test/java/org/molgenis/armadillo/storage/LocalStorageServiceTest.java, armadillo/src/test/java/org/molgenis/armadillo/storage/ParquetUtilsTest.java
https://github.com/molgenis/GCC/issues/1298
how to test:
- https://preview-armadillo-pr-861.dev.molgenis.org/storage/projects/test/objects/blaat%2Fpancreatic.parquet/metadata
Additional testing:
- upload parquet/csv file
- go to [swagger](https://preview-armadillo-pr-861.dev.molgenis.org/swagger-ui/index.html#/storage/getMetadataOfTable), select project + folder + uploaded table in metadata endpoint
- check if metadata is succesfully returned
todo:
=> feat: metadata endpoint

ui/src/views/Profiles.vue
=> fix: make styling of profile page scoped

ui/src/views/Workspaces.vue
=> style: remove heading from workspaces page

ui/src/components/RemoteFile.vue, ui/src/views/RemoteFiles.vue
=> style: make insight logging page more functional on small screen

README.md
We'll need to update this to a working version, but let's remove it for now.
how to test:
todo:
=> fix: remove docker for now

.circleci/config.yml
=> fix: attempt to fix build
