molgenis/molgenis-service-armadillo

datashield/src/main/java/org/molgenis/datashield/DataController.java
datashield/src/main/java/org/molgenis/datashield/DataShieldSession.java
datashield/src/main/java/org/molgenis/datashield/DataShieldUtils.java
datashield/src/test/java/org/molgenis/datashield/DataControllerTest.java
datashield/src/test/java/org/molgenis/datashield/DataShieldSessionTest.java
datashield/src/test/java/org/molgenis/datashield/DataShieldUtilsTest.java
datashield/test.http
r/src/main/java/org/molgenis/r/service/RConfig.java

Use content negotiation to determine evaluate raw or not.
Use separate thread pool for evaluation of all requests.
Evaluation returns a CompletableFuture.
Session keeps last result.

feat: async evaluation

---

datashield/src/main/java/org/molgenis/datashield/AuthConfig.java
datashield/src/main/java/org/molgenis/datashield/DataController.java
datashield/src/main/java/org/molgenis/datashield/DataShieldSession.java
datashield/src/main/java/org/molgenis/datashield/DataShieldUtils.java
datashield/src/main/java/org/molgenis/datashield/pojo/DataShieldCommand.java
datashield/src/main/java/org/molgenis/datashield/service/DataShieldConnectionFactoryImpl.java
datashield/src/main/resources/application.yml
datashield/src/test/java/org/molgenis/datashield/DataControllerTest.java
datashield/src/test/java/org/molgenis/datashield/DataShieldSessionTest.java
datashield/src/test/java/org/molgenis/datashield/DataShieldUtilsTest.java
datashield/src/test/java/org/molgenis/datashield/pojo/DataShieldCommandTest.java
datashield/src/test/java/org/molgenis/datashield/service/DataShieldConnectionFactoryImplTest.java
datashield/test.http
r/src/main/java/org/molgenis/r/service/RExecutorService.java
r/src/main/java/org/molgenis/r/service/RExecutorServiceImpl.java
r/src/test/java/org/molgenis/r/service/RExecutorServiceImplTest.java

Removes json execution endpoints, adds endpoints to:
* Load tables workspace from minio into environment
* List tables
* Assign symbol from table
* Assign symbol from expression, also async
* List symbols
* Delete symbol
* Debug any expression (role SU only)

feat: implement DSI methods

---

armadillo/src/main/java/org/molgenis/armadillo/ArmadilloSession.java
armadillo/src/main/java/org/molgenis/armadillo/command/impl/CommandsImpl.java

Initially, `ArmadilloSession` was the bean with `@SessionScope`.
But we had to keep track of the last command so the `CommandsImpl` became the session bean.
That's when we should've moved the `@PreDestroy` cleanup method to the `CommandsImpl` as well :)

fix: move cleanup annotation to the session bean

---

armadillo/src/main/java/org/molgenis/armadillo/ArmadilloSession.java

RServe completely hides the port number in a private field, so if we want to log it we need to read it using reflection.

feat: debug port when detaching

---

armadillo/pom.xml
armadillo/src/main/java/org/molgenis/armadillo/info/RMetrics.java
armadillo/src/main/java/org/molgenis/armadillo/info/RProcessEndpoint.java
r/src/main/java/org/molgenis/r/REXPParser.java
r/src/main/java/org/molgenis/r/model/RProcess.java
r/src/main/java/org/molgenis/r/service/ProcessService.java
r/src/main/java/org/molgenis/r/service/ProcessServiceImpl.java
r/src/test/java/org/molgenis/r/REXPParserTest.java
r/src/test/java/org/molgenis/r/service/ProcessServiceImplTest.java

Until the docker PR is merged you can use `registry.molgenis.org/molgenis/ds-60-rserver-363:PR-52`
TODO:

feat: expose r process info on actuator endpoints

---

docker/docker-compose.yml

expose only exposes to the other containers, but to work in intellij you need the
rserve port to be exposed to the host. Also, it uses 6311, not 6312.

chore(docker): fix port number and intellij workflow

---

armadillo/pom.xml
armadillo/src/main/java/org/molgenis/armadillo/service/ArmadilloConnectionFactoryImpl.java
armadillo/src/main/resources/application.yml
docker/docker-compose.yml
docker/rebuild.sh
docker/rserver/Dockerfile
pom.xml
r/pom.xml

Blocks on: https://github.com/datashield/docker-armadillo-rserver-base/pull/8.
The resourcer package needs to be uninstalled on the rserver image, before this version of Armadillo will run.

fix: remove resources package as base package

---

pom.xml

Bumps `spring-boot-starter-parent` to [2.5.12](https://github.com/spring-projects/spring-boot/releases/tag/v2.5.12), which contains an upgrade to Spring Framework 5.3.18 which contains a fix for [CVE-2022-22965](https://tanzu.vmware.com/security/cve-2022-22965)

chore: bump spring-boot-starter-parent

---

.mvn/jvm.config

See https://github.com/spotify/fmt-maven-plugin/issues/99

Fix: build fails because fmt-maven-plugin breaks with jdk 16 

---

.pre-commit-config.yaml
README.md

Let's try using `pre-commit` to manage our commit hooks. This one triggers a `mvn fmt:format` on commit.
1. Install `pre-commit` with `pip` or `brew`  (see https://pre-commit.com/index.html#1-install-pre-commit)
2. In the repo, run `pre-commit install`

Add pre-commit that auto-formats code on commit

---

Jenkinsfile
armadillo/pom.xml
pom.xml

~TODO: figure out which image to get from https://console.cloud.google.com/gcr/images/distroless/GLOBAL/~
See: https://github.com/GoogleContainerTools/jib/blob/master/docs/default_base_image.md#migration-from-pre-30
See: https://stackoverflow.com/questions/67130671/why-jib-dropped-support-for-distroless-base-image
We will follow jib's recommendations and let jib choose the base image

chore: migrate to java 17

---

r/src/main/java/org/molgenis/r/service/PackageServiceImpl.java

This can happen when you whitelist packages that are not present in Rserve

Fix: improve error message when loading non-existing packages

---

ui/src/api/api.ts
ui/src/helpers/errorProcessing.ts
ui/src/router.ts
ui/src/views/Profiles.vue
ui/src/views/Projects.vue
ui/src/views/ProjectsExplorer.vue
ui/src/views/Users.vue

return complete object instead of json when 401 or 403 and when unauthorized error presented, redirect and refresh (separate function)
closes #309
To test: 
1) Run in dev mode using `yarn dev`
2) login on localhost:8080
3) go to localhost:8081
4) logout on 8080
5)  click on a tab in 8081
should redirect to login instead of giving cryptic error now.

fix: redirect to login when unauthorized

---

ui/src/components/Navbar.vue

since swagger is not available in production mode anyways (only dev), in dev mode enter swagger via /swagger-ui/index.html
fix #321

fix(navbar): remove api link

---

ui/src/views/Profiles.vue

text actually is "stop", not "online", so the stopProfile would never be called
fix #323

fix(profiles): check if status is online instead of text

---

ui/src/components/Table.vue

to prevent scrambled columns trying to fit everything when you have a lot of users/projects

style(table): set max width for columns to 30%

---

ui/src/views/Projects.vue

all buttons are disabled in edit mode, so we dont need to clear the new project
fix #355

fix(projects): dont refresh new project on edit project

---

armadillo/src/main/java/org/molgenis/armadillo/command/impl/CommandsImpl.java
armadillo/src/main/java/org/molgenis/armadillo/controller/DataController.java
armadillo/src/main/java/org/molgenis/armadillo/profile/ProfileScopeConfig.java

elevate permissions for regular users when selecting/viewing profile(s)
fixes #385
fixes #405
Code to test #385:
``` r
library(DSI)
library(dsBaseClient)
library(DSMolgenisArmadillo)
armadillo_url <- "http://localhost:8080/"
token <- armadillo.get_token(armadillo_url)
builder <- DSI::newDSLoginBuilder()
builder$append(server = "armadillo",
url = armadillo_url,
token = token,
table = "cohort1/2_1-core-1_0/nonrep",
driver = "ArmadilloDriver")
logindata <- builder$build()
conns <- datashield.login(logins = logindata, symbol = "core_nonrep", variables = c("coh_country"), assign = TRUE)
```
Code to test #405:
``` r
library('MolgenisArmadillo')
library(DSI)
library(dsBaseClient)
library(DSMolgenisArmadillo)
armadillo_url <- "http://localhost:8080/"
token <- armadillo.get_token(armadillo_url) …
```

fix: run list profiles and select profile as system

---

.gitignore
README.md
armadillo/src/main/java/org/molgenis/armadillo/controller/CurrentUserController.java
armadillo/src/main/java/org/molgenis/armadillo/info/AuthInfoContributor.java
armadillo/src/main/java/org/molgenis/armadillo/security/AuthConfig.java
armadillo/src/main/java/org/molgenis/armadillo/security/JwtDecoderConfig.java
armadillo/src/main/java/org/molgenis/armadillo/security/JwtDecoderConfigLocal.java
armadillo/src/main/resources/application.yml
docker-compose.yml

motivation: useful for automated test.
You can run it using the option:
`java -jar molgenis-armadillo-3.*.jar -Dspring.profiles.active=basic`
Also, you can then run the script in datashield as listed in docker/test/test-local.R
Furthermore updated documentation explaining how best to create your own application.yml, or when developing how to set the secrets via -D options.

feat: add profile that only runs on basic auth

---

armadillo/src/main/java/org/molgenis/armadillo/command/Commands.java
armadillo/src/main/java/org/molgenis/armadillo/command/impl/CommandsImpl.java
armadillo/src/main/java/org/molgenis/armadillo/controller/DataController.java
armadillo/src/test/java/org/molgenis/armadillo/command/impl/CommandsImplTest.java
armadillo/src/test/java/org/molgenis/armadillo/controller/DataControllerTest.java
r/build.gradle
r/src/main/java/org/molgenis/r/service/RExecutorService.java
r/src/main/java/org/molgenis/r/service/RExecutorServiceImpl.java
r/src/test/java/org/molgenis/r/service/RExecutorServiceImplTest.java

Work in progress. Doesn't work yet (creating the file in RExecutorServiceImpl.java#127 doesn't work yet). 
Prerequisites in armadillo:
1) Add the caravan-uniform profile in the armadillo ui:
name: uniform
image: datashield/armadillo-rserver_caravan-uniform:2.0.0
packages whitelist: dsOmics, dsBase, resourcer
2) Start the profile
3) Create project omics in the UI
4) Create folder test
5) Download the testfile: https://github.com/isglobal-brge/brge_data_large/blob/master/data/gse66351_1.rda
6) Upload it in your test folder (increase max file size in `application.yml`:
```spring:
servlet:
multipart:
max-file-size: 500MB
max-request-size: 500MB
```
)
R code (for testing):
Creating resources (make sure v1.4 of the resourcer is used, this shouldn't be needed when this feature is complete(?)): …

feat: create resource file with token when calling resource 

---

armadillo/src/main/java/org/molgenis/armadillo/controller/StorageController.java
armadillo/src/main/java/org/molgenis/armadillo/storage/ArmadilloStorageService.java
armadillo/src/main/java/org/molgenis/armadillo/storage/LocalStorageService.java
armadillo/src/main/java/org/molgenis/armadillo/storage/MinioStorageService.java
armadillo/src/main/java/org/molgenis/armadillo/storage/StorageService.java
armadillo/src/test/java/org/molgenis/armadillo/controller/StorageControllerTest.java

So that we don't run into the max size of a byte array to make sure we can use resources over 2.15GB
fixes #458

fix: retrieve filesize of resource from filepath

---

ui/src/types/api.d.ts
ui/src/views/Profiles.vue

- Extracted Datashield Seed from Options into seperate Profiles UI column.
- Hidden datashield.seed from Options UI column.
- (To set a datashield.seed or to set a different datashield.seed, use the options column. Changing or setting a datashield seed throught the "Datashield Seed" column is disabled.)
- Added functionality to automatically asign an unused datashield seed when a new profile is created from the UI.
-

Feat: datashield seed UI column

---

README.md

- Added documentation on what to do as a developer when running into the "host.docker.internal" error on resourcer whitelisted profiles on Linux (primarily Arch)
Closes #508

docs: host.docker.internal error on resourcer profiles in Linux

---

docs/ops/installing.md

...instead of nginx. We don't recommend or support this, but if anyone wants to use it, they can at their own risk using this documentation.

docs: add documentation for running armadillo using apache

---

r/src/main/java/org/molgenis/r/service/RExecutorServiceImpl.java
r/src/test/java/org/molgenis/r/service/RExecutorServiceImplTest.java
scripts/release/release-test.R

instead of dataframe
closes #591
How to test: 
Execute code in https://github.com/molgenis/molgenis-service-armadillo/issues/591 and see that the type now equals dataframe instead of tibble.

fix: #591 loadTable returns tibble for arrow 13+

---

settings.gradle

This is a script/sub tree for some future rock related projects.
- rockctl is a rock controller to query its status and sessions

Add a rock controller

---

docs/ops/install/install_apache.md
docs/ops/install/install_docker.md
docs/ops/install/install_java.md
docs/ops/installing.md
scripts/install/README.md
scripts/install/armadillo-setup.sh
scripts/install/conf/application.yml

Documentation bugs:
- it requires OIDC config otherwise Armadillo crashes
- removing the section from `/etc/armadillo/application.yml` fixed it
- adding profile `datashield/rock-dolomite-xenon:latest` ends with
- >   Error: Could not start [xenon]: SyntaxError: The string did not match the expected pattern..
- expected auto install of rock

Update docs for #594

---

armadillo/src/main/java/org/molgenis/armadillo/security/AuthConfig.java

When login to Armadillo docs worked fine ... never tested it anonymous which redirected to OIDC .. that is now fixed

fix(docs): make docs available for anonymous

---

docker/ci/README.md
docker/ci/docker-compose.yml

Fixes #660
It seems using a different image tag should fix this ... using `:local` in `armadillo-compose` config.
```yml
image: molgenis/molgenis-armadillo:local
```
It does not work on MacOS (SegFault) so let's see what CICD does

bug: cicd should use local image

---

docker/ci/docker-compose.yml

Trying to run the demo set in armadillo-compose.zip Linux users have to run using sudo and got error for `${PWD}` in `docker-compose.yml`
> WARN[0000] The "PWD" variable is not set. Defaulting to a blank string.

fix(demo): relative path

---

CONTRIBUTING.md
application.template.yml
build.gradle

This plugin https://github.com/ben-manes/gradle-versions-plugin adds command `https://github.com/ben-manes/gradle-versions-plugin`
It prints and builds in `cat build/dependencyUpdates/report.txt`
Currently this gives
```txt
------------------------------------------------------------
: Project Dependency Updates (report to plain text file)
------------------------------------------------------------
The following dependencies are using the latest milestone version:
- com.c4-soft.springaddons:spring-security-oauth2-test-webmvc-addons:4.5.1
- com.google.auto.value:auto-value:1.10.4
- com.google.auto.value:auto-value-annotations:1.10.4
- com.google.code.gson:gson:2.10.1
- io.spring.dependency-management:io.spring.dependency-management.gradle.plugin:1.1.4
- …
```

chore: gradle/add upgrade checker

---

CONTRIBUTING.md
armadillo/build.gradle
build.gradle
r/build.gradle
ui/build.gradle

This tool mentioned upgrade sonar so let's see what CICD tells
See #695 
Install plugin `se.patrikerdes.use-latest-versions`
Run repeatedly
```bash
./gradlew useLatestVersions
./gradlew useLatestVersionsCheck
```
and manually upgrade mentions items
```bash
find . -type f -name "build.gradle" -exec echo {} \; -exec grep YOUR_KEY_WORD {}  \;
```

chore: add update tool

---

scripts/release/test-cases/upload-resource.R

how to test:
- Rerun the release test up to and including line 88 (`upload_resource`)

chore: remove spinner from resource upload

---

armadillo/src/main/java/org/molgenis/armadillo/storage/ArmadilloLinkFile.java
armadillo/src/main/java/org/molgenis/armadillo/storage/LocalStorageService.java
armadillo/src/test/java/org/molgenis/armadillo/storage/ArmadilloLinkFileTest.java

how to test:
- create a link
- see that the number of columns in the preview is the same as the number of variables selected
todo:

fix: info endpoint returns incorrect number of columns for linkfile

---

armadillo/src/main/java/org/molgenis/armadillo/storage/ArmadilloStorageService.java
armadillo/src/main/java/org/molgenis/armadillo/storage/ArmadilloWorkspace.java
armadillo/src/main/java/org/molgenis/armadillo/storage/LocalStorageService.java
armadillo/src/main/java/org/molgenis/armadillo/storage/StorageService.java
armadillo/src/test/java/org/molgenis/armadillo/storage/ArmadilloStorageServiceTest.java
armadillo/src/test/java/org/molgenis/armadillo/storage/ArmadilloWorkspaceTest.java
armadillo/src/test/java/org/molgenis/armadillo/storage/LocalStorageServiceTest.java

Testing this is incredibly annoying. I tested it on the dev server and it kept dying, we really need to look into that. Maybe we should just trust that I've tested it, and just do the code review, if not, here is how I tested it:
How to test:
On the devserver, I put the build version of this PR, it's called `armadillo-workspace-4.x-SNAPSHOT.jar`
Check the version of armadillo on the devserver by going there in the browser and see what version is presented in the top menu, if it's not 4.3-SNAPSHOT (we have to investigate why my new build results in 4.3), then it's the incorrect version. To fix the version, ssh to demo server as root (see serverlist for IP)
``` bash
cd /usr/share/armadillo/application
service armadillo stop
rm armadillo.jar
ln -s armadillo-workspace-4.x-SNAPSHOT.jar …
```

fix: #124 throw error when workspace too big to store on device

---

r/build.gradle
r/src/main/java/org/molgenis/r/rock/RockConnection.java

This is a refactor of the rock connection class, using the spring `RestClient`, rather than the (deprecated) `RestTemplate`, as suggested by spring. This should prevent blocking calls and overall work more smoothly. 
Included apache in gradle, because default calls will go via jetty, which fails:
https://github.com/spring-projects/spring-boot/issues/38960

refactor: rock connection

---

armadillo/src/main/java/org/molgenis/armadillo/storage/ArmadilloStorageService.java
armadillo/src/main/java/org/molgenis/armadillo/storage/ArmadilloWorkspace.java
armadillo/src/test/java/org/molgenis/armadillo/storage/ArmadilloStorageServiceTest.java
armadillo/src/test/java/org/molgenis/armadillo/storage/ArmadilloWorkspaceTest.java

part of #772
how to test:
Run armadillo locally, then run in R:
``` R
library(MolgenisArmadillo)
library(DSMolgenisArmadillo)
library(dsBaseClient)
library(DSI)
demo_url <- "https://dev-armadillo.molgenis.org/"
demo_url <- "http://localhost:8080"
demo_token <- armadillo.get_token(demo_url)
builder <- DSI::newDSLoginBuilder()
builder$append(
server = "armadillo",
url = demo_url,
profile = "xenon",
driver = "ArmadilloDriver",
token = demo_token
)
logindata <- builder$build()
conns <- DSI::datashield.login(logins = logindata, assign = T)
datashield.assign.table(conns, "nonrep", "lifecycle/core/nonrep")
fit <- ds.glmSLMA(
formula = "preg_no ~ 1+ height_mes_m + preg_fever + preg_gain_mes + ethn1_p + weight_f1 + smk_p + death_child_age",
family = "gaussian",
newobj = "test",
dataName = …
```

fix: throw proper error message when workspace over 2GBs

---

armadillo/src/main/java/org/molgenis/armadillo/info/RProcessEndpoint.java
armadillo/src/main/java/org/molgenis/armadillo/metadata/ProfileService.java
armadillo/src/main/java/org/molgenis/armadillo/security/AuthConfig.java

how to test:
- Start up armadillo
- Run this commandline: 
`curl 'http://localhost:8080/actuator/prometheus' -i -X GET`
No stacktraces will show up in the armadillo logs and the version of the R serve profiles are visible in the commandline output:
```
rserve_processes_current{environment="default",} 2.0
rserve_processes_current{environment="xenon",} 2.0
```
For code review:
- Check if this is secure enough. Removed pre authorise on class `ProfileService`, but put it back on all the methods of that class, so that the `.getAll` class can be called with `runAsSystem` in the `doWithConnection` method of `RProcessEndpoint`. I think that we don't leak anything that is not supposed to be leaked, but better to check twice. I'm for instance a bit worried about leakin the `seed`, but I think that …

feat: expose actuator/prometheus endpoint

---

ui/src/views/ProjectsExplorer.vue

how to test:
- go to https://preview-armadillo-pr-806.dev.molgenis.org/
- go to a table
- click on the create view button in right top corner
- see that the "Preview" in the top corner disappears, as well as the columns in the bottom left of the view screen
Before:
After:
todo:

fix: #804 dont show preview and columns when in create linkfile view

---

ui/src/App.vue
ui/src/api/api.ts
ui/src/helpers/utils.ts
ui/tests/unit/helpers/utils.spec.ts

how to test:
- Once built, go to https://preview-armadillo-pr-812.dev.molgenis.org/
- Login, see if the diskspace error is there:
- If it's not there, the PR works (it did show up on every preview)

fix: #811 correct typing on diskspace and check for NaN

---

armadillo/src/main/java/org/molgenis/armadillo/storage/ArmadilloStorageService.java
armadillo/src/test/java/org/molgenis/armadillo/storage/ArmadilloStorageServiceTest.java

fix: show link files

---

ui/src/components/Navbar.vue

how to test:
Open the preview, click on the docs link, see the docs are opened
https://preview-armadillo-pr-834.dev.molgenis.org/

fix: #833 documentation link not working

---

armadillo/src/main/java/org/molgenis/armadillo/audit/AuditEventPublisher.java
armadillo/src/main/java/org/molgenis/armadillo/controller/ProfilesController.java
armadillo/src/main/java/org/molgenis/armadillo/controller/ProfilesStatusResponse.java
armadillo/src/main/java/org/molgenis/armadillo/profile/DockerService.java
armadillo/src/main/java/org/molgenis/armadillo/security/AuthConfig.java
armadillo/src/test/java/org/molgenis/armadillo/TestSecurityConfig.java
armadillo/src/test/java/org/molgenis/armadillo/controller/ProfilesControllerDockServiceNullTest.java
armadillo/src/test/java/org/molgenis/armadillo/controller/ProfilesControllerTest.java

how to test:
- start and call endpoint `/ds-profiles/status`
(probably not very informative on preview because dockermanagement isn't enabled there (?)) 
Example of output:
```
[
{
"image": "datashield/rock-lemon-donkey:latest",
"name": "default",
"config": "[JAVA_VERSION=jdk-21.0.5+11, ROCK_VERSION=2.1.1, DSBASE_VERSION=6.3.1, DSMEDIATION_VERSION=0.0.3, DSEXPOSOME_VERSION=2.0.9, DSTIDYVERSE_VERSION=v1.0.1, DSOMICS_VERSION=v1.0.18-2, DSMTL_VERSION=0.9.9, DSSURVIVAL_VERSION=v2.1.3]",
"status": "RUNNING"
},
{
"image": "datashield/rock-lemon-donkey:latest",
"name": "donkey",
"status": "NOT_FOUND"
},
{
"image": "datashield/rock-dolomite-xenon:2.0.0",
"name": "xenon",
"config": "[JAVA_VERSION=jdk-21.0.2+13, ROCK_VERSION=2.0.1, DSBASE_VERSION=6.3.0, DSMEDIATION_VERSION=0.0.3, …
```

feat: Monitoring endpoint for getting versions and status of profiles

---

docs/pages/install_management/armadillo_install.md
docs/pages/install_management/armadillo_migrate_2_to_3.md
docs/pages/install_management/armadillo_migrate_3_to_4.md
docs/pages/install_management/armadillo_migrate_4_to_5.md
docs/pages/install_management/index.md
mkdocs.yml
ui/src/App.vue
ui/src/components/Footer.vue

BREAKING CHANGE: Migrate to armadillo 5 running Java 21

---

armadillo/src/main/java/org/molgenis/armadillo/audit/AuditEventPublisher.java
armadillo/src/main/java/org/molgenis/armadillo/controller/InsightController.java
armadillo/src/main/java/org/molgenis/armadillo/model/DockerImageInfo.java
armadillo/src/main/java/org/molgenis/armadillo/profile/DockerService.java
armadillo/src/main/java/org/molgenis/armadillo/storage/LocalStorageService.java
armadillo/src/test/java/org/molgenis/armadillo/controller/InsightControllerTest.java
armadillo/src/test/java/org/molgenis/armadillo/profile/DockerServiceTest.java

how to test:
- Install armadillo locally
- Make sure docker is running with some images pulled in there
- Go to new swagger endpoint: http://localhost:8080/swagger-ui/index.html#/insight/getDockerImages
- Click on Execute and see all images there (including non-running)
todo:

feat: all docker images endpoint

---

armadillo/src/main/java/org/molgenis/armadillo/audit/AuditEventPublisher.java
armadillo/src/main/java/org/molgenis/armadillo/controller/DevelopmentController.java
armadillo/src/main/java/org/molgenis/armadillo/exceptions/ImageRemoveFailedException.java
armadillo/src/main/java/org/molgenis/armadillo/profile/DockerService.java
armadillo/src/test/java/org/molgenis/armadillo/controller/DevelopmentControllerTest.java
armadillo/src/test/java/org/molgenis/armadillo/profile/DockerServiceTest.java

how to test:
- Install armadillo locally
- Make sure docker is running with some images pulled in there
- Go to new swagger endpoint: http://localhost:8080/swagger-ui/index.html#/developer/deleteDockerImage
- Make sure there's an image in your local docker that isn't running and you want to delete, copy it's id (images tab in docker desktop and Image ID column)
- Paste the ID in the endpoint
- Click on Execute and see all images there (including non-running)
todo:

feat: remove docker image endpoint

---

armadillo/src/main/java/org/molgenis/armadillo/controller/DevelopmentController.java
armadillo/src/main/java/org/molgenis/armadillo/controller/ProfileResponse.java
armadillo/src/main/java/org/molgenis/armadillo/metadata/InitialProfileConfig.java
armadillo/src/main/java/org/molgenis/armadillo/metadata/ProfileConfig.java
armadillo/src/main/java/org/molgenis/armadillo/metadata/ProfileService.java
armadillo/src/main/java/org/molgenis/armadillo/profile/DockerService.java
armadillo/src/test/java/org/molgenis/armadillo/DataShieldOptionsImplTest.java
armadillo/src/test/java/org/molgenis/armadillo/command/impl/CommandsImplTest.java
armadillo/src/test/java/org/molgenis/armadillo/controller/ProfilesControllerDockServiceNullTest.java
armadillo/src/test/java/org/molgenis/armadillo/controller/ProfilesControllerTest.java
armadillo/src/test/java/org/molgenis/armadillo/metadata/ProfileConfigTest.java
armadillo/src/test/java/org/molgenis/armadillo/metadata/ProfileServiceTest.java
armadillo/src/test/java/org/molgenis/armadillo/profile/DockerServiceTest.java
ui/src/types/api.d.ts
ui/src/views/Profiles.vue

Now that we are automatically updating profiles, we want to include more information about the profiles installed.
- Check that the columns "Version ID", "Image Size", "Creation Date" and "Install Date" are showing
- Add a new profile (or start an existing profile), and check that these fields are populated with information. Note that 
"Version ID" and "Creation Date" depend on these properties being set in the profile, so they may not show depending the profile you are starting.

feat: extra profile info

---

scripts/release/test-cases/xenon-exposome.R

GGplot2 package has been updated - they've changed the structure of the plot object to slots rather than list elements which broke an exposome test. Now I just test for class of created object rather than names of that object which is more robust (and backwards compatible).
## How to test:
- Code review
- Check CI green

fixed test following ggplot update
